id: ACDBC9771
base_file: fE7AC.txt
type: translation
source_metadata:
  languages:
  - en
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-05-30 20:48:48.977079
  last_modified_at: 2022-05-30 20:48:48.977092
